import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, CircleDot, Ruler, ShieldCheck, Wrench } from "lucide-react";
import { CartDrawer } from "@/components/cart-drawer";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

export const metadata: Metadata = { title: "Biblioteca técnica | Bulonera Agroindustrial", description: "Equivalencias de medidas, roscas y grados de resistencia para elegir bulonería correctamente." };

const inchSizes = [["1/8", "3,18"], ["3/16", "4,76"], ["1/4", "6,35"], ["5/16", "7,94"], ["3/8", "9,53"], ["7/16", "11,11"], ["1/2", "12,70"], ["9/16", "14,29"], ["5/8", "15,88"], ["3/4", "19,05"], ["7/8", "22,23"], ["1", "25,40"], ["1 1/4", "31,75"], ["1 1/2", "38,10"], ["2", "50,80"]];
const metricWrenches = [["M4", "7"], ["M5", "8"], ["M6", "10"], ["M8", "13"], ["M10", "17"], ["M12", "19"], ["M14", "22"], ["M16", "24"], ["M18", "27"], ["M20", "30"], ["M22", "32"], ["M24", "36"]];

export default function AdvicePage() {
  return <><Header /><CartDrawer /><main>
    <section className="advice-hero"><div className="container"><span className="eyebrow">Centro de asesoramiento</span><h1>Biblioteca técnica</h1><p>Referencias rápidas para medir, comparar y comprar fijaciones con menos margen de error.</p></div></section>
    <nav className="advice-index"><div className="container"><a href="#equivalencias">Pulgadas a mm</a><a href="#medicion">Cómo medir</a><a href="#roscas">Roscas</a><a href="#resistencia">Resistencia</a><a href="#checklist">Antes de comprar</a></div></nav>

    <section id="equivalencias" className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Conversión rápida</span><h2><Ruler size={28} /> Pulgadas a milímetros</h2></div></div><div className="technical-grid"><div className="card"><table className="table technical-table"><thead><tr><th>Pulgadas</th><th>Milímetros</th></tr></thead><tbody>{inchSizes.map(([inch, mm]) => <tr key={inch}><td>{inch}&quot;</td><td>{mm} mm</td></tr>)}</tbody></table></div><article className="card technical-note"><h3>Regla de conversión</h3><strong>1 pulgada = 25,4 mm</strong><p>La equivalencia dimensional no significa que una rosca métrica y una rosca en pulgadas sean intercambiables. También deben coincidir el paso y el perfil de la rosca.</p><div className="formula">pulgadas × 25,4 = milímetros</div></article></div></div></section>

    <section id="medicion" className="section alt"><div className="container"><div className="section-head"><div><span className="eyebrow">Identificación</span><h2>Cómo medir un bulón</h2></div></div><div className="grid grid-3"><article className="card guide-step"><b>1</b><CircleDot /><h3>Diámetro</h3><p>Medí el diámetro exterior de la rosca con calibre. En M8 será aproximadamente 8 mm.</p></article><article className="card guide-step"><b>2</b><Ruler /><h3>Largo</h3><p>En una cabeza hexagonal se mide desde debajo de la cabeza hasta la punta. En una cabeza fresada se incluye la cabeza.</p></article><article className="card guide-step"><b>3</b><Wrench /><h3>Paso</h3><p>Medí la distancia entre dos crestas. En pulgadas suele expresarse como cantidad de hilos por pulgada.</p></article></div></div></section>

    <section id="roscas" className="section"><div className="container technical-grid"><div><span className="eyebrow">Compatibilidad</span><h2>Rosca métrica, UNC y UNF</h2><div className="card"><table className="table"><thead><tr><th>Sistema</th><th>Característica</th><th>Uso habitual</th></tr></thead><tbody><tr><td>Métrica</td><td>Diámetro y paso en mm</td><td>Industria, automotor y maquinaria</td></tr><tr><td>UNC</td><td>Rosca gruesa en pulgadas</td><td>Montaje general y materiales blandos</td></tr><tr><td>UNF</td><td>Rosca fina en pulgadas</td><td>Ajuste fino, automotor y vibraciones</td></tr></tbody></table></div></div><div><span className="eyebrow">Referencia</span><h2>Llaves para métrica</h2><div className="card"><table className="table technical-table"><thead><tr><th>Rosca</th><th>Llave habitual</th></tr></thead><tbody>{metricWrenches.map(([thread, wrench]) => <tr key={thread}><td>{thread}</td><td>{wrench} mm</td></tr>)}</tbody></table></div></div></div></section>

    <section id="resistencia" className="section alt"><div className="container"><div className="section-head"><div><span className="eyebrow">Selección del material</span><h2><ShieldCheck size={28} /> Grados de resistencia</h2></div></div><div className="grid resistance-grid"><article className="card"><h3>Grado SAE 2</h3><p>Acero de baja o media resistencia para aplicaciones livianas sin grandes esfuerzos: soportes, cerramientos y montajes generales.</p></article><article className="card"><h3>Grado SAE 5</h3><p>Resistencia media para automotor, maquinaria y equipos. Se identifica habitualmente por tres líneas radiales en la cabeza.</p></article><article className="card"><h3>Clase métrica 8.8</h3><p>Uso estructural y mecánico general. Es una de las opciones más comunes para maquinaria y montaje.</p></article><article className="card"><h3>Clase métrica 10.9 y 12.9</h3><p>Mayor resistencia mecánica. Deben utilizarse con tuercas compatibles y el torque indicado por el fabricante.</p></article><article className="card"><h3>Inoxidable A2 y A4</h3><p>A2 para humedad y exterior moderado. A4 ofrece mayor resistencia a ambientes agresivos, químicos o salinos.</p></article></div></div></section>

    <section id="checklist" className="section"><div className="container technical-grid"><div><span className="eyebrow">Compra segura</span><h2>Datos que conviene confirmar</h2><div className="purchase-checklist">{["Diámetro nominal", "Largo útil", "Paso de rosca", "Sistema métrico o pulgadas", "Tipo y forma de cabeza", "Clase de resistencia", "Material o terminación", "Cantidad y presentación"].map((item) => <span key={item}><CheckCircle2 size={18} /> {item}</span>)}</div></div><article className="card technical-help"><h2>¿Todavía tenés dudas?</h2><p>Traé una muestra al local o enviá fotos junto con una medida tomada con calibre. Nuestro equipo puede ayudarte a identificarla.</p><Link className="button" href="/#contacto">Solicitar asesoramiento</Link></article></div></section>
  </main><Footer /></>;
}
